[package]
name = "othello"
version = "0.3.0"
authors = ["Harenayo"]
edition = "2021"
description = "A crate for Othello"
readme = "README.md"
repository = "https://github.com/harenayo/othello-rs"
license = "MIT"
